select DISTINCT TABLE_CATALOG, TABLE_NAME, COLUMN_NAME 
from INFORMATION_SCHEMA.COLUMNS c
where exists (select TABLE_NAME from INFORMATION_SCHEMA.TABLES where c.TABLE_NAME = TABLE_NAME and TABLE_TYPE = 'BASE TABLE')
;

select TABLE_CATALOG, TABLE_NAME from INFORMATION_SCHEMA.TABLES where TABLE_TYPE = 'BASE TABLE';

select DISTINCT COLUMN_NAME from INFORMATION_SCHEMA.COLUMNS;